services:
  bridge:
    ports: !reset []
    networks:
      - default
      - homelab

  lab-ui:
    ports: !reset []
    networks:
      - default
      - homelab

  postgres:
    ports: !reset []

  miden-node:
    ports: !reset []

networks:
  homelab:
    external: true
